# Copyright (c) 2020 Nam Seob Seo
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

[workspace]

members = [
    "svg-web-service",
    "svg-converter"
]

#[patch.crates-io]
#lexical-core = {git = 'https://github.com/Alexhuszagh/rust-lexical' }
