[package]
name = "svg-web-service"
version = "0.1.0"
authors = ["Nam Seob Seo <nsclass@gmail.com>"]
edition = "2018"

[dependencies]
svg-converter = { path = "../svg-converter" }

actix = "0.9"
actix-web = "2.0"
actix-rt = "1.1.1"

futures = "0.3.5"
env_logger = "0.7"
bytes = "0.5"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"