[package]
name = "svg-web-service"
version = "0.1.0"
authors = ["Nam Seob Seo <nsclass@gmail.com>"]
edition = "2018"

[dependencies]
svg-converter = { path = "../svg-converter" }

actix = "0.7"
actix-web = "0.7"

futures = "0.1"
env_logger = "0.5"
bytes = "0.4"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
