# Copyright (c) 2020 Nam Seob Seo
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

[package]
name = "svg-web-service"
version = "0.1.0"
authors = ["Nam Seob Seo <nsclass@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "app"

[dependencies]
svg-converter = { path = "../svg-converter" }

actix-web = "2"
actix-rt = "1"
config = "0.10"
dotenv = "0.15"
serde = {version = "1", features = ["derive"] }
serde_json = "1.0"
futures = "0.3.5"
bytes = "0.5"

eyre = "0.6"
color-eyre = "0.5"
tracing = "0.1"
tracing-futures = "0.2"
tracing-log = { version = "0.1.1", features = ["env_logger"] }
actix-files = "0.2.2"
tracing-subscriber = { version = "0.2", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.1.6"

[dev-dependencies]
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }
assert-json-diff = "1.1.0"
