[package]
name = "svg-converter"
version = "0.1.0"
authors = ["Nam Seob Seo <nsclass@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.20.1"
image-base64 = "0.1"
ndarray = "0.12.1"
rand = "0.6.1"
failure ="0.1"