[package]
name = "svg-converter"
version = "0.1.0"
authors = ["Nam Seob Seo <nsclass@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.23.6"
image-base64 = "0.1"
ndarray = "0.13.1"
rand = "0.7.3"
thiserror = "1.0.20"